# Generated by Django 2.1.2 on 2018-11-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_followed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='arefollowing',
            field=models.ManyToManyField(to='profiles.Profile'),
        ),
    ]
