# Generated by Django 2.1.2 on 2018-11-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_arefollowing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='isfollowing',
            new_name='followers',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='arefollowing',
            new_name='following',
        ),
    ]
