# Generated by Django 2.1.2 on 2018-11-13 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20181113_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'ordering': ('-created_at',)},
        ),
    ]
