# Generated by Django 2.1.2 on 2018-10-19 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_auto_20181019_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_views', to='articles.ArticlesModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='articleview',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articleview',
            name='user',
        ),
        migrations.DeleteModel(
            name='ArticleView',
        ),
    ]
