# Generated by Django 2.1.2 on 2018-10-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20181019_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlestat',
            name='count',
        ),
    ]
